export { default as BagePlaceholder } from './BagePlaceholder.astro';
export { default as CardPlaceholder } from './CardPlaceholder.astro';
export { default as ImagePlaceholder } from './ImagePlaceholder.astro';
export { default as ListPlaceholder } from './ListPlaceholder.astro';
export { default as Skeleton } from './Skeleton.astro';
export { default as TestimonialPlaceholder } from './TestimonialPlaceholder.astro';
export { default as TextPlaceholder } from './TextPlaceholder.astro';
export { default as VideoPlaceholder } from './VideoPlaceholder.astro';
export { default as WidgetPlaceholder } from './WidgetPlaceholder.astro';
